---
title: "How Leaders Actually Make Decisions"
format: html
---

In this chapter, we are going to discuss, presenting your results to people at various levels of an organization. This will include people ranging from management, and other analysts, to people in the C-Suite. There are some elements that are common when you are presenting your results, and then there are other elements which are going to be more specific, depending on what a person’s responsibilities include.

I’ve had the opportunity to manage multi-million dollar accounts for a fortune 1000 company, I’ve also run two volunteer nonprofits, a chapter of Amnesty International, and the Chicago Apple User Group.My work also includes several nonprofit social service organizations. I’ve also run my own vacation rental business, and I’ve done a lot of volunteer work. Therefore, I can speak from a wide range of experience on business needs.

Leaders do not think analytically very often, instead they spend the majority of their thinking about strategy. Therefore if you want to communicate in their terms, you are best off if you include strategy in your presentations and results. This chapter will demonstrate how you can communicate analytical results with people who think in terms of strategy.

12.1 Reducing the distance between business and analytics goals

12.1.1 HBR: The High Cost of Misaligned Business and Analytics Goals 12.1.2 <https://hbr.org/2024/06/the-high-cost-of-misaligned-business-and-analytics-goals> 12.2 How to find out what is most important to leadership

12.2.1 Vision, Mission and Values 12.2.2 Current and future strategies 12.2.3 Do not check only once if you are working on the most important issue(s)—Check multiple times if you are actually working on the most important issue(s) to leadership <https://www.youtube.com/watch?v=BkLzo_oNVho>

12.3 How to build and test the most accurate models for the most important things to leadership

12.3.1 Leaders rarely test their vision or goals before they launch them - that’s our job after the vision has been launched 12.3.2 Leadership is wrong a lot of the time because they rely on confirming evidence. Also seek the strongest disconfirming testing and evidence so you have the best prepared case. 12.4 How data scientists make decisions

12.4.1 What is most important? 12.4.2 Make many models of what is most important 12.4.3 Find highest accuracy and most predictive results 12.4.4 Total transparency and reproducibility 12.5 How to move from the most accurate model, to strategy, to tactics the organization can actually do

12.5.1 Most accurate - we already have that part 12.5.2 Strategy - What is strategy 12.5.3 How to derive tactics from the models with the strongest predictive accuracy 12.6 Understand the difference between how your neurons make a decision, how executives make decisions, and what the data shows.

12.6.1 Testable and falsifiable hypothesis why the most accurate models get rejected all the time by leadership. 12.7 How to build the largest probability of acceptance for your solution.

12.7.1 Leaders will almost always go for the solution with the best support, not necessarily the solution with the highest accuracy. 12.7.2 Best support means both best accuracy and most defensible. Leaders ALWAYS want to be prepared to respond to criticism, attacks, threats from competition, comments from investors, etc. 12.7.3 The stronger the support, the more likely the solution is to be acted upon, not the most accurate. 12.8 How to read financial statements

12.8.1 How to determine profit, loss, expenses 12.9 Seven examples of scientists who told the truth

12.9.1 Thomas Jefferson 12.9.2 Al-Biruni 12.9.3 Hypatia 12.9.4 Florentine Codex 12.9.5 Sima Chen 12.9.6 Dr. Wangari Mathaii 12.9.7 Jacques Costeau 12.10 How to manage A-Players (the best in the business)

12.10.1 How to recruit and hire A-Players 12.10.2 How to start with a team of A-Players and move forward from there 12.11 Why great ideas don’t win and bad ideas don’t die (one reason is the sunk cost effect)

12.11.1 Seconday gains 12.11.2 Why people, groups and organizations say no 12.11.3 Incorrectly perceived threat/danger 12.11.4 Possible steps to take to help the best ideas win and ideas that fail to lose 12.11.5 What leadership perceives to be its source of truth: Reports, experts, past performance, financials 12.11.6 What leadership perceives to be its source of power 12.12 Sometimes leaders believe they can pursue their ideas and are protected by evidence from:

12.12.1 Following recommendations of highly paid consultants 12.12.2 Following recommendations of the legal department 12.12.3 Claiming they are beating the competition (especially if they are beating the competition at their own game!) 12.12.4 Money (either revenue or investment) 12.12.5 Office politics (the C-suite loves this, etc.) 12.13 How to tell a story in a way that people will want to listen

12.13.1 Know your audience 12.13.2 Three parts usually works best 12.13.3 Set it up as tension-release 12.14 How to ask intelligent questions so you look for things no one has evver looked for before

12.15 How to listen (from a professional counselor)

12.15.1 The big bang of professional listening - how it all started 12.15.2 Experimental evidence regarding the best environment for listening. 12.16 How to determine an organizatoin’s true values and culture

12.16.1 All organizations have positive values they tell the world (usually in a mission statements among other places) 12.16.2 Also consider what they actually do and tolerate and reward on a consistent basis as the reflection of their true values, some of which might not be as flattering. For example, based on what they actually consistently do and tolerate and reward, their true values might be copying ideas from competitors rather than innovating, keeping practices that cause custoemr turnover and frustrate staff, rewarding loyalty to leadership over results, never truly testing any processes (letting the customer test the product or process), using the courts as your customer service system, tolerating scandals and crappy performance, not truly fixing any issues once they are brought forward. Your customers should not also be your beta testers. 12.17 The problems when organizations use ideas to move forward and improve results

12.17.1 Ideas have three problems: They are free, easy, and sound great. 12.17.2 Much better results if they use falsifable hypotheses 12.17.3 Failure must always be a very real option in testing. Make it safe to say the test failed. 12.18 How to predict the strongest predictors determined by analytics

12.19 How to successfuly manage 2 or 3 or 4 or more steps ahead of the competition

12.20 What executives and managers need to know to make the wisest possible decisions

12.20.1 A very basic introduction to financial reporting 12.20.2 Always give the best service you can possibly do: The Ritz Carlton method 12.20.3 Help your manager make the best possible decisions 12.20.4 Have empathy for your manager’s—and customer’s— situations 12.20.5 don’t need them in any way 12.20.6 Have a great story to tell—How to create a great story 12.20.7 Br prepared with strong counterexamples 12.20.8 include uncertainty 12.20.9 tell the (hard) truth, prepare them for criticism 12.20.10 Communicating results with staff who have Profit and Loss responsibility 12.20.11 Vision, mission, values - what is the central question? 12.20.12 Financials 12.20.13 The higher up the org chart, the more you will be working with vision, stragety, financials 12.20.14 Communicating with customers and vendors 12.20.15 Communicating ROI and other results of data science 12.20.16 Social media and more 12.21 One of your own

12.22 Post your results on social media
